# Generated by Django 5.2 on 2026-02-22 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('base_url', models.URLField(unique=True)),
                ('region_default', models.CharField(default='Global', max_length=100)),
                ('category_default', models.CharField(default='General', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('list_page_pattern', models.CharField(default='', max_length=200)),
                ('article_link_selector', models.CharField(default='a[href]', max_length=200)),
                ('title_selector', models.CharField(default='h1', max_length=200)),
                ('content_selector', models.CharField(default='article p', max_length=200)),
                ('published_at_selector', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField(blank=True)),
                ('url', models.URLField(unique=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(default='General', max_length=100)),
                ('region', models.CharField(default='Global', max_length=100)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='collector.source')),
            ],
            options={
                'ordering': ['-published_at', '-scraped_at'],
                'indexes': [models.Index(fields=['source'], name='collector_a_source__7c3ffe_idx'), models.Index(fields=['category'], name='collector_a_categor_16039e_idx'), models.Index(fields=['region'], name='collector_a_region_c291b6_idx'), models.Index(fields=['published_at'], name='collector_a_publish_7a4708_idx')],
            },
        ),
    ]
